var htmlConfig = {
	"bookConfig": {
		"bookPageStretch": "false",
		"maxHeightToSmallMode": 300,
		"appName": "华名陶 瓷如意",
		"totalPageCount": 62,
		"largePageWidth": 751.181,
		"largePageHeight": 992.126,
		"normalPath": "files\/large\/",
		"largePath": "files\/large\/",
		"thumbPath": "files\/thumb\/",
		"ToolBarsSettings": "",
		"TitleBar": "",
		"appLogoLinkURL": "",
		"bookTitle": "华名陶",
		"bookDescription": "华名陶",
		"ButtonsBar": "",
		"ShareButton": "",
		"ThumbnailsButton": "",
		"ThumbnailsButtonVisible": "Show",//底部拖拽条是否可见
		"ZoomButton": "",
		"ZoomButtonVisible": "Show",//底部加号缩放按钮是否可见
		"FlashDisplaySettings": "",
		"MainBgConfig": "",
		"bgBeginColor": "#7891b9",//背景顶部颜色
		"bgEndColor": "#fce",//背景底部颜色
		"bgMRotation": 90,//背景色旋转角度
		"pageBackgroundColor": "#FFFFFF",
		"flipshortcutbutton": "Hide",//翻转快捷键是否可见（中间部分左右箭头）
		"BookMargins": "",
		"topMargin": 10,
		"bottomMargin": 10,
		"leftMargin": 10,
		"rightMargin": 10,
		"HTMLControlSettings": "",
		"linkconfig": "",
		"LinkDownColor": "#0000FF",
		"LinkAlpha": 0.4,
		"OpenWindow": "Blank",
		"BookMarkButtonVisible": "Hide",
		"productName": "华名陶",
		"homePage": "http:\/\/bdu.com\/",
		"isFlipPdf": "false",
		"TableOfContentButtonVisible": "Hide",
		"searchTextJS": "files\/search\/book_config.js",
		"searchPositionJS": "files\/search\/text_position[%d].js", //搜索功能每个页面一个 JS,主要说明文字位置和内容
		"articleListPath": "..\/articles\/config\/articleList.json",
		"FlipSound": "Yes",
		"QRCode": "Hide",//二维码是否显示
		"appLogoIcon": "", //左上角 LOGO 图片 URL
		"HomeURL": "", //logo链接
		"appLogoOpenWindow": "Blank",
		"toolbarColor": "#eeeeee",
		"iconColor": "#fbfbd9",
		"loadingPicture": "files\/extfile\/loadingPicture.png",//页面加载显示的logo图
		"loadingCaptionColor": "#000",//页面加载中间文字和图标颜色
		"loadingBackground": "#fff",//页面加载背景颜色
		"logoHeight": 30,
		"logoTop": 0,
		"logoPadding": 0,
		"HomeButtonVisible": "Hide",//主页按钮是否显示
		"ShareButtonVisible": "Hide",//分享按钮是否显示
		"thumbnailAlpha": 70,
		"FullscreenButtonVisible": "Show",//全屏按钮是否显示
		"SearchButtonVisible": "Hide",//搜索按钮是否显示
		"leastSearchChar": 2,
		"PrintButtonVisible": "Hide",//打印按钮是否显示
		"printWatermarkFile": "",
		"BackgroundSoundButtonVisible": "Hide",
		"BackgroundSoundURL": "", //背景音乐
		"BackgroundSoundLoop": "-1", //-1循环播放 1 播放一次
        "bgSoundVol": "50", //背景音乐音量
		"HelpButtonVisible": "Hide",
		"helpContentFileURL": "",
		"helpWidth": 400,
		"helpHeight": 450,
		"showHelpContentAtFirst": "No",
		"aboutButtonVisible": "Hide",//右上角按钮
		"aboutContactInfoTxt": "<info><title><\/title><desc><\/desc><logo>ZmlsZXMvZXh0ZmlsZS9hYm91dENvbnRhY3RJbmZvVHh0LnBuZw==<\/logo><keys><key name=\"QXV0aG9y\" type=\"Author\">UkVEQUdSSUNPTEE=<\/key><key name=\"QWRkcmVzcw==\" type=\"Address\">河南郑州华南市场<\/key><key name=\"RW1haWw=\" type=\"Email\"> Joozo@139.cn==<\/key><key name=\"TGluaw==\" type=\"Link\">aHR0cHM6Ly93d3cucmVkYWdyaWNvbGEuY29tLw==<\/key><key name=\"UGhvbmU=\" type=\"Phone\">186-0070-9077=<\/key><\/keys><\/info>",
		"AutoPlayButtonVisible": "Hide",
		"autoPlayAutoStart": "No",
		"SlideshowAutoPlay": false,
		"autoPlayDuration": 3,
		"SlideshowPlayInterval": 5,
		"autoPlayLoopCount": "1",
		"minZoomWidth": 403,
		"minZoomHeight": 518,
		"mouseWheelFlip": "Yes", //鼠标滚轮翻转 Yes No
		"DownloadButtonVisible": "Hide",
		"DownloadURL": "https:\/\/8.com\/download\/download-pdf-file.php?str=x0DZh9GTud3bENXamYDO0MzMxUTPkl0av9mY",
		"UserInforSetting": "",
		"backGroundImgURL": "",
		"LeftShadowWidth": 15,
		"LeftShadowAlpha": 0.6,
		"RightShadowWidth": 20,
		"RightShadowAlpha": 0.3,
		"OriginPageIndex": 1,
		"RightToLeft": "No",
		"flippingTime": 0.3,
		"retainBookCenter": "Yes",
		"FlipStyle": "Flip",
		"totalPagesCaption": "",
		"pageNumberCaption": "",
		"googleAnalyticsID": "",
		"UIBaseURL": "",
		"language": "Chinaese",
		"AboutAddress": " 华名陶",
		"AboutAuthor": "Joozo",
		"AboutEmail": "joozo@joozo.cn",
		"AboutMobile": "(+86) 18600709077",
		"AboutWebsite": "http:\/\/joozo.cn\/",
		"AboutDescription": "",
		"VideoButtonVisible": "Hide",
		"SlideshowButtonVisible": "Hide",
		"addPaperCoil": "No",
		"AnnotationButtonVisible": "Hide",
		"CompanyLogoFile": "files\/extfile\/aboutContactInfoTxt.png",
		"bleedAreaLeft": "0%",
		"bleedAreaRight": "0%",
		"bleedAreaTop": "0%",
		"bleedAreaBottom": "0%",
		"HardPageEnable": "No",
		"HardInnerPageEnable": "No",
		"borderColor": "#562e0b",
		"BindingType": "side",
		"hardCoverBorderWidth": "8",
		"outerCoverBorder": "Yes",
		"cornerRound": "8",
		"coverTexture": "none",
		"iconFontColor": "#022c17",
		"formBackgroundColor": "#495867",
		"formFontColor": "#eeeeee",
		"backgroundOpacity": "90",
		"autoDoublePage": "Auto",  //默认值Auto , No只显示单页,控制显示一页还是两页
		"searchKeywordFontColor": "#FFB000",
		"backgroundPosition": "Stretch",
		"CurlingPageCorner": "No",
		"updatePageURL": "True",
		"isTheBookOpen": "No",
		"FlipDirection": "0",
		"InstructionsButtonVisible": "Hide",
		"showInstructionOnStart": "No",
		"showThicknessOnMobile": "No",
		"highDefinitionConversion": "Yes",
		"pageNumColor": "#111111",
		"backgroundScene": "None",
		"ShowTopLeftShadow": "No",
		"maxWidthToSmallMode": 400,
		"hideMiniFullscreen": "No",
		"isStopMouseMenu": "Yes",
		"haveAdSense": "No",
		"adSenseWidth": 200,
		"adSenseHeight": 200,
		"adSenseLeft": 50,
		"adSenseTop": 50,
		"adSenseClientId": "",
		"SelectTextButtonVisible": "Hide",
		"leftRightPnlShowOption": "none",
		"ToolBarAlpha": "1",
		"enablePageBack": "Show",
		"loadingCaption": "",
		"phoneFlipShortcutButton": "Hide",
		"CreatedTime": 1660318649,
		"loadingCaptionFontSize": "20",
		"loadingPictureHeight": "150",
		"showLoadingGif": "Yes",
		"loadingDisplayTime": "0",
		"loadingVideo": "",
		"buttonsSortXML": [],
		"phoneToolbarType": "image",
		"phoneIconNumber": "6",
		"showGotoButtonsAtFirst": "No",
		"addCurrentPage": "No",
		"EmailButtonVisible": "Hide",
		"btnShareWithEmailSubject": "",
		"btnShareWithEmailBody": "{link}",
		"thumbnailColor": "#333333",
		"ThumbnailSize": "small",
		"isHideTabelOfContentNodes": "yes",
		"searchFontColor": "#FFFFFF",
		"searchHightlightColor": "#FDC606",
		"SelectTextButtonIcon": "",
		"SupportOperatePageZoom": "Yes",
		"maxZoomWidth": "0",
		"defaultZoomWidth": "0",
		"ZoomMapVisible": "Hide",
		"downloadConfig": "",
		"PhoneButtonVisible": "Hide",
		"PhoneButtonIcon": "",
		"PhoneNumbers": "",
		"WeChatShareButtonVisible": "Hide",
		"WeChatShareButtonIcon": "",
		"MagnifierButtonVisible": "Hide",
		"DoubleSinglePageButtonVisible": "No",
		"toolbarAlwaysShow": "No",
		"ToolBarVisible": "Yes",
		"searchbarAlwaysShowOnMobile": "No",
		"middleZoomWidth": "0",
		"MessageButtonVisible": "Hide",
		"showLeaveMessage": "Yes",
		"articleTime": "",
		"articleTitle": "",
		"QRPath": "",
		"loadPreviewImage": "Yes",
		"removeLoad": "No",
		"pageHighlightType": "book",
		"leftMarginOnMobile": "0",
		"topMarginOnMobile": "0",
		"rightMarginOnMobile": "0",
		"bottomMarginOnMobile": "0",
		"thicknessWidthType": "thick",
		"thicknessColor": "#FFFFFF",
		"SingleModeBanFlipToLastPage": "No",
		"isSingleBookFullWindowOnMobile": "no",
		"restorePageVisible": "no",
		"useTheAliCloudChart": false,
		"textClarityEnhancement": "0",
		"showBookInstructionOnStart": "false",
		"securitySetting": "No Security",
		"passwordTips": "\u8bf7\u8054\u7cfb<a href='mailto:author@sample.com'>\u4f5c\u8005\u83b7\u53d6\u6b64\u4e66",
		"OnlyOpenInWechat": "false",
		"NoWechatSharing": "Hide",
		"OnlyOpenInIframe": "No",
		"OnlyOpenInIframeInfo": "\u60a8\u6ca1\u6709\u9605\u8bfb\u6743\u9650\u3002",
		"showLinkHint": "No",
		"updateURLForPage": "False",
		"appLargeLogoIcon": "",
		"appLargeLogoURL": "",
		"LargeLogoPosition": "top-left",
		"LargeLogoTarget": "Blank",
		"isFixLogoSize": "No",
		"logoFixWidth": "0",
		"logoFixHeight": "0",
		"languageSetting": "Spanish"
	},
	"aliasConfig": {
		"appName": ["", "", ""],
		"totalPageCount": [],
		"largePageWidth": [],
		"largePageHeight": [],
		"normalPath": [],
		"largePath": [],
		"thumbPath": [],
		"ToolBarsSettings": [],
		"TitleBar": [],
		"appLogoIcon": ["appLogoIcon"],
		"appLogoLinkURL": ["appLogoLinkURL"],
		"bookTitle": [],
		"bookDescription": [],
		"ButtonsBar": [],
		"ShareButton": [],
		"ShareButtonVisible": ["socialShareButtonVisible"],
		"ThumbnailsButton": [],
		"ThumbnailsButtonVisible": ["enableThumbnail"],
		"ZoomButton": [],
		"ZoomButtonVisible": ["enableZoomIn"],
		"FlashDisplaySettings": [],
		"MainBgConfig": [],
		"bgBeginColor": ["bgBeginColor"],
		"bgEndColor": ["bgEndColor"],
		"bgMRotation": ["bgMRotation"],
		"backGroundImgURL": ["mainbgImgUrl", "innerMainbgImgUrl"],
		"pageBackgroundColor": ["pageBackgroundColor"],
		"flipshortcutbutton": [],
		"BookMargins": [],
		"topMargin": [],
		"bottomMargin": [],
		"leftMargin": [],
		"rightMargin": [],
		"HTMLControlSettings": [],
		"linkconfig": [],
		"LinkDownColor": ["linkOverColor"],
		"LinkAlpha": ["linkOverColorAlpha"],
		"OpenWindow": ["linkOpenedWindow"],
		"searchColor": [],
		"searchAlpha": [],
		"SearchButtonVisible": ["searchButtonVisible"],
		"productName": [],
		"homePage": [],
		"enableAutoPlay": ["autoPlayAutoStart"],
		"autoPlayDuration": ["autoPlayDuration"],
		"autoPlayLoopCount": ["autoPlayLoopCount"],
		"BookMarkButtonVisible": [],
		"googleAnalyticsID": ["googleAnalyticsID"],
		"OriginPageIndex": [],
		"HardPageEnable": ["isHardCover"],
		"UIBaseURL": [],
		"RightToLeft": ["isRightToLeft"],
		"LeftShadowWidth": ["leftPageShadowWidth"],
		"LeftShadowAlpha": ["pageShadowAlpha"],
		"RightShadowWidth": ["rightPageShadowWidth"],
		"RightShadowAlpha": ["pageShadowAlpha"],
		"ShortcutButtonHeight": [],
		"ShortcutButtonWidth": [],
		"AutoPlayButtonVisible": ["enableAutoPlay"],
		"DownloadButtonVisible": ["enableDownload"],
		"DownloadURL": ["downloadURL"],
		"HomeButtonVisible": ["homeButtonVisible"],
		"HomeURL": ["btnHomeURL"],
		"BackgroundSoundURL": ["bacgroundSoundURL"],
		"PrintButtonVisible": ["enablePrint"],
		"toolbarColor": ["mainColor", "barColor"],
		"loadingBackground": ["mainColor", "barColor"],
		"BackgroundSoundButtonVisible": ["enableFlipSound"],
		"FlipSound": ["enableFlipSound"],
		"MiniStyle": ["userSmallMode"],
		"retainBookCenter": ["moveFlipBookToCenter"],
		"totalPagesCaption": ["totalPageNumberCaptionStr"],
		"pageNumberCaption": ["pageIndexCaptionStrs"]
	},
	"aliasLanguage": {
		"frmPrintbtn": ["frmPrintCaption"],
		"frmPrintall": ["frmPrintPrintAll"],
		"frmPrintcurrent": ["frmPrintPrintCurrentPage"],
		"frmPrintRange": ["frmPrintPrintRange"],
		"frmPrintexample": ["frmPrintExampleCaption"],
		"btnLanguage": ["btnSwicthLanguage"],
		"btnTableOfContent": ["btnBookMark"],
		"btnExitFullscreen": ["btnDisableFullScreen"],
		"btnFullscreen": ["btnFullScreen"],
		"btnHome": ["homebtnHelp"],
		"btnMore": ["btnMoreOptionsLeft"],
		"frmToc": ["btnBookMark"],
		"frmSearch": ["btnSearch"],
		"frmLinkLabel": ["lblLink"]
	},
	"meta": {
		"title": "RA128 - Julio 2022",
		"description": "RA128 - Julio 2022",
		"url": "https:\/\/online.fliphtml5.com\/fttlu\/qavm\/index.html",
		"pageCount": 84,
		"template": "Popular",
		"theme": "Default",
		"pageWidth": 751.181,
		"pageHeight": 992.126,
		"htmlTemplate": "Popular"
	},
	"project-config": [],
	"bmtConfig": {
		"tabs": [],
		"onSideEdge": true
	},
	"videoList": [],
	"staticAd": {
		"haveAd": true,
		"interval": 3000,
		"data": [{
			"src": "files\/extfile\/ED2093923100B90BDA6C7702D41F709F.jpg",
			"url": "http:\/\/baidu.com\/"
		}]
	},
	"ols": [],
	"slideshow": [],
	"flipByAudio": null,
	"downloadconfig": null,
	"assistantConfig": null,
	"phoneNumber": [],
	"bookPlugin": null,
	"slider": "[]",
	"": [{
		"l": "files\/large\/1.jpg",
		"t": "files\/thumb\/1.jpg"
	}, {
		"l": "files\/large\/2.jpg",
		"t": "files\/thumb\/2.jpg"
	}, {
		"l": "files\/large\/3.jpg",
		"t": "files\/thumb\/3.jpg"
	}, {
		"l": "files\/large\/4.jpg",
		"t": "files\/thumb\/4.jpg"
	}, {
		"l": "files\/large\/5.jpg",
		"t": "files\/thumb\/5.jpg"
	}, {
		"l": "files\/large\/6.jpg",
		"t": "files\/thumb\/6.jpg"
	}, {
		"l": "files\/large\/7.jpg",
		"t": "files\/thumb\/7.jpg"
	}, {
		"l": "files\/large\/8.jpg",
		"t": "files\/thumb\/8.jpg"
	}, {
		"l": "files\/large\/9.jpg",
		"t": "files\/thumb\/9.jpg"
	}, {
		"l": "files\/large\/10.jpg",
		"t": "files\/thumb\/10.jpg"
	}, {
		"l": "files\/large\/11.jpg",
		"t": "files\/thumb\/11.jpg"
	}, {
		"l": "files\/large\/12.jpg",
		"t": "files\/thumb\/12.jpg"
	}, {
		"l": "files\/large\/13.jpg",
		"t": "files\/thumb\/13.jpg"
	}, {
		"l": "files\/large\/14.jpg",
		"t": "files\/thumb\/14.jpg"
	}, {
		"l": "files\/large\/15.jpg",
		"t": "files\/thumb\/15.jpg"
	}, {
		"l": "files\/large\/16.jpg",
		"t": "files\/thumb\/16.jpg"
	}, {
		"l": "files\/large\/17.jpg",
		"t": "files\/thumb\/17.jpg"
	}, {
		"l": "files\/large\/18.jpg",
		"t": "files\/thumb\/18.jpg"
	}, {
		"l": "files\/large\/19.jpg",
		"t": "files\/thumb\/19.jpg"
	}, {
		"l": "files\/large\/20.jpg",
		"t": "files\/thumb\/20.jpg"
	}, {
		"l": "files\/large\/21.jpg",
		"t": "files\/thumb\/21.jpg"
	}, {
		"l": "files\/large\/22.jpg",
		"t": "files\/thumb\/22.jpg"
	}, {
		"l": "files\/large\/23.jpg",
		"t": "files\/thumb\/23.jpg"
	}, {
		"l": "files\/large\/24.jpg",
		"t": "files\/thumb\/24.jpg"
	}, {
		"l": "files\/large\/25.jpg",
		"t": "files\/thumb\/25.jpg"
	}, {
		"l": "files\/large\/26.jpg",
		"t": "files\/thumb\/26.jpg"
	}, {
		"l": "files\/large\/27.jpg",
		"t": "files\/thumb\/27.jpg"
	}, {
		"l": "files\/large\/28.jpg",
		"t": "files\/thumb\/28.jpg"
	}, {
		"l": "files\/large\/29.jpg",
		"t": "files\/thumb\/29.jpg"
	}, {
		"l": "files\/large\/30.jpg",
		"t": "files\/thumb\/30.jpg"
	}, {
		"l": "files\/large\/31.jpg",
		"t": "files\/thumb\/31.jpg"
	}, {
		"l": "files\/large\/32.jpg",
		"t": "files\/thumb\/32.jpg"
	}, {
		"l": "files\/large\/33.jpg",
		"t": "files\/thumb\/33.jpg"
	}, {
		"l": "files\/large\/34.jpg",
		"t": "files\/thumb\/34.jpg"
	}, {
		"l": "files\/large\/35.jpg",
		"t": "files\/thumb\/35.jpg"
	}, {
		"l": "files\/large\/36.jpg",
		"t": "files\/thumb\/36.jpg"
	}, {
		"l": "files\/large\/37.jpg",
		"t": "files\/thumb\/37.jpg"
	}, {
		"l": "files\/large\/38.jpg",
		"t": "files\/thumb\/38.jpg"
	}, {
		"l": "files\/large\/39.jpg",
		"t": "files\/thumb\/39.jpg"
	}, {
		"l": "files\/large\/40.jpg",
		"t": "files\/thumb\/40.jpg"
	}, {
		"l": "files\/large\/41.jpg",
		"t": "files\/thumb\/41.jpg"
	}, {
		"l": "files\/large\/42.jpg",
		"t": "files\/thumb\/42.jpg"
	}, {
		"l": "files\/large\/43.jpg",
		"t": "files\/thumb\/43.jpg"
	}, {
		"l": "files\/large\/44.jpg",
		"t": "files\/thumb\/44.jpg"
	}, {
		"l": "files\/large\/45.jpg",
		"t": "files\/thumb\/45.jpg"
	}, {
		"l": "files\/large\/46.jpg",
		"t": "files\/thumb\/46.jpg"
	}, {
		"l": "files\/large\/47.jpg",
		"t": "files\/thumb\/47.jpg"
	}, {
		"l": "files\/large\/48.jpg",
		"t": "files\/thumb\/48.jpg"
	}, {
		"l": "files\/large\/49.jpg",
		"t": "files\/thumb\/49.jpg"
	}, {
		"l": "files\/large\/50.jpg",
		"t": "files\/thumb\/50.jpg"
	}, {
		"l": "files\/large\/51.jpg",
		"t": "files\/thumb\/51.jpg"
	}, {
		"l": "files\/large\/52.jpg",
		"t": "files\/thumb\/52.jpg"
	}, {
		"l": "files\/large\/53.jpg",
		"t": "files\/thumb\/53.jpg"
	}, {
		"l": "files\/large\/54.jpg",
		"t": "files\/thumb\/54.jpg"
	}, {
		"l": "files\/large\/55.jpg",
		"t": "files\/thumb\/55.jpg"
	}, {
		"l": "files\/large\/56.jpg",
		"t": "files\/thumb\/56.jpg"
	}, {
		"l": "files\/large\/57.jpg",
		"t": "files\/thumb\/57.jpg"
	}, {
		"l": "files\/large\/58.jpg",
		"t": "files\/thumb\/58.jpg"
	}, {
		"l": "files\/large\/59.jpg",
		"t": "files\/thumb\/59.jpg"
	}, {
		"l": "files\/large\/60.jpg",
		"t": "files\/thumb\/60.jpg"
	}]
};
